import React, { useContext, useState, useRef } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Animated, Dimensions, Platform, Modal, TextInput, ScrollView } from 'react-native';
import { ThemeContext } from '../ThemeContext';
import { StudyContext } from '../StudyContext';
import GlassView from '../components/GlassView';
import { RotateCw, ChevronLeft, ChevronRight, Plus, Trash2, Sparkles, X, FileText, Type } from 'lucide-react';
import { AIService } from '../services/AIService';

const { width } = Dimensions.get('window');

const FlashcardsScreen = () => {
    const { theme } = useContext(ThemeContext);
    const { flashcards, setFlashcards, deleteFlashcard, addFlashcards, files } = useContext(StudyContext);
    const [currentCardIndex, setCurrentCardIndex] = useState(0);
    const [isFlipped, setIsFlipped] = useState(false);
    const flipAnim = useRef(new Animated.Value(0)).current;

    const [showGenerateModal, setShowGenerateModal] = useState(false);
    const [generationMode, setGenerationMode] = useState<'topic' | 'file'>('topic');
    const [topicInput, setTopicInput] = useState('');
    const [selectedFileId, setSelectedFileId] = useState<string | null>(null);
    const [isGenerating, setIsGenerating] = useState(false);

    const flipCard = () => {
        if (isFlipped) {
            Animated.spring(flipAnim, {
                toValue: 0,
                friction: 8,
                tension: 10,
                useNativeDriver: true,
            }).start();
        } else {
            Animated.spring(flipAnim, {
                toValue: 180,
                friction: 8,
                tension: 10,
                useNativeDriver: true,
            }).start();
        }
        setIsFlipped(!isFlipped);
    };

    const nextCard = () => {
        if (currentCardIndex < flashcards.length - 1) {
            setIsFlipped(false);
            flipAnim.setValue(0);
            setCurrentCardIndex(currentCardIndex + 1);
        }
    };

    const prevCard = () => {
        if (currentCardIndex > 0) {
            setIsFlipped(false);
            flipAnim.setValue(0);
            setCurrentCardIndex(currentCardIndex - 1);
        }
    };

    const handleDeleteCard = () => {
        if (flashcards.length === 0) return;
        const cardId = flashcards[currentCardIndex].id;
        deleteFlashcard(cardId);
        if (currentCardIndex >= flashcards.length - 1) {
            setCurrentCardIndex(Math.max(0, flashcards.length - 2));
        }
        setIsFlipped(false);
        flipAnim.setValue(0);
    };

    const handleGenerate = async () => {
        if (generationMode === 'topic' && !topicInput.trim()) {
            alert('Please enter a topic');
            return;
        }
        if (generationMode === 'file' && !selectedFileId) {
            alert('Please select a file');
            return;
        }

        setIsGenerating(true);
        try {
            // Mock AI Generation
            const source = generationMode === 'topic' ? topicInput : files.find(f => f.id === selectedFileId)?.name;
            const newCards = Array.from({ length: 15 }).map((_, i) => ({
                id: Date.now().toString() + i,
                front: `Question ${i + 1} about ${source}`,
                back: `Answer ${i + 1} generated by AI`,
                topic: source || 'General',
                date: new Date().toLocaleDateString()
            }));

            // Simulate delay
            await new Promise(resolve => setTimeout(resolve, 1500));

            addFlashcards(newCards);
            setShowGenerateModal(false);
            setTopicInput('');
            setSelectedFileId(null);
            alert(`Generated 15 flashcards for ${source}`);
        } catch (error) {
            alert('Generation failed');
        } finally {
            setIsGenerating(false);
        }
    };

    const frontInterpolate = flipAnim.interpolate({
        inputRange: [0, 180],
        outputRange: ['0deg', '180deg'],
    });

    const backInterpolate = flipAnim.interpolate({
        inputRange: [0, 180],
        outputRange: ['180deg', '360deg'],
    });

    const frontOpacity = flipAnim.interpolate({
        inputRange: [89, 90],
        outputRange: [1, 0],
    });

    const backOpacity = flipAnim.interpolate({
        inputRange: [89, 90],
        outputRange: [0, 1],
    });

    const currentCard = flashcards[currentCardIndex];

    // Colorful borders logic
    const getBorderColor = (index: number) => {
        const colors = ['#FF3B30', '#34C759', '#007AFF', '#FFCC00', '#AF52DE', '#FF2D55'];
        return colors[index % colors.length];
    };

    return (
        <View style={styles.container}>
            <View style={styles.headerRow}>
                <Text style={[styles.headerTitle, { color: theme.colors.text }]}>Flashcards</Text>
                <View style={styles.headerActions}>
                    <TouchableOpacity onPress={handleDeleteCard} style={styles.iconButton}>
                        <GlassView style={styles.glassIcon}>
                            <Trash2 size={20} color={theme.colors.danger} />
                        </GlassView>
                    </TouchableOpacity>
                    <TouchableOpacity style={styles.iconButton} onPress={() => setShowGenerateModal(true)}>
                        <GlassView style={styles.glassIcon}>
                            <Sparkles size={20} color={theme.colors.primary} />
                        </GlassView>
                    </TouchableOpacity>
                </View>
            </View>

            <Modal visible={showGenerateModal} transparent animationType="fade">
                <View style={styles.modalOverlay}>
                    <GlassView style={[styles.modalContent, { backgroundColor: theme.colors.card }]} intensity={90}>
                        <View style={styles.modalHeader}>
                            <Text style={[styles.modalTitle, { color: theme.colors.text }]}>Generate Flashcards</Text>
                            <TouchableOpacity onPress={() => setShowGenerateModal(false)}>
                                <X size={24} color={theme.colors.text} />
                            </TouchableOpacity>
                        </View>

                        <View style={styles.tabRow}>
                            <TouchableOpacity
                                style={[styles.tab, generationMode === 'topic' && { backgroundColor: theme.colors.primary }]}
                                onPress={() => setGenerationMode('topic')}
                            >
                                <Type size={16} color={generationMode === 'topic' ? '#FFF' : theme.colors.text} />
                                <Text style={[styles.tabText, { color: generationMode === 'topic' ? '#FFF' : theme.colors.text }]}>Topic</Text>
                            </TouchableOpacity>
                            <TouchableOpacity
                                style={[styles.tab, generationMode === 'file' && { backgroundColor: theme.colors.primary }]}
                                onPress={() => setGenerationMode('file')}
                            >
                                <FileText size={16} color={generationMode === 'file' ? '#FFF' : theme.colors.text} />
                                <Text style={[styles.tabText, { color: generationMode === 'file' ? '#FFF' : theme.colors.text }]}>From Dump</Text>
                            </TouchableOpacity>
                        </View>

                        {generationMode === 'topic' ? (
                            <TextInput
                                style={[styles.input, { color: theme.colors.text, borderColor: theme.colors.border }]}
                                placeholder="Enter a topic (e.g., 'Photosynthesis')"
                                placeholderTextColor={theme.colors.textSecondary}
                                value={topicInput}
                                onChangeText={setTopicInput}
                            />
                        ) : (
                            <ScrollView style={styles.fileList}>
                                {files.filter(f => f.type === 'text' || f.type === 'manual').map(file => (
                                    <TouchableOpacity
                                        key={file.id}
                                        style={[
                                            styles.fileOption,
                                            selectedFileId === file.id && { borderColor: theme.colors.primary, backgroundColor: theme.colors.primary + '20' }
                                        ]}
                                        onPress={() => setSelectedFileId(file.id)}
                                    >
                                        <FileText size={16} color={theme.colors.text} />
                                        <Text style={[styles.fileOptionText, { color: theme.colors.text }]}>{file.name}</Text>
                                    </TouchableOpacity>
                                ))}
                                {files.filter(f => f.type === 'text' || f.type === 'manual').length === 0 && (
                                    <Text style={{ color: theme.colors.textSecondary, textAlign: 'center', marginTop: 20 }}>
                                        No text files or notes found in Study Dump.
                                    </Text>
                                )}
                            </ScrollView>
                        )}

                        <TouchableOpacity
                            style={[styles.generateButton, { backgroundColor: theme.colors.primary }]}
                            onPress={handleGenerate}
                            disabled={isGenerating}
                        >
                            {isGenerating ? (
                                <Text style={styles.generateButtonText}>Generating...</Text>
                            ) : (
                                <>
                                    <Sparkles size={18} color="#FFF" />
                                    <Text style={styles.generateButtonText}>Generate 15 Cards</Text>
                                </>
                            )}
                        </TouchableOpacity>
                    </GlassView>
                </View>
            </Modal>

            <View style={styles.cardContainer}>
                {flashcards.length > 0 ? (
                    <View style={styles.cardWrapper}>
                        {/* Front Side */}
                        <Animated.View style={[
                            styles.cardFace,
                            {
                                backgroundColor: theme.colors.card,
                                transform: [{ rotateY: frontInterpolate }],
                                opacity: frontOpacity,
                                zIndex: isFlipped ? 0 : 1,
                                borderColor: getBorderColor(currentCardIndex),
                                borderWidth: 2,
                            }
                        ]}>
                            <GlassView style={styles.glassContent} intensity={40}>
                                <Text style={[styles.cardTopic, { color: theme.colors.textSecondary }]}>{currentCard.topic}</Text>
                                <Text style={[styles.cardText, { color: theme.colors.text }]}>{currentCard.front}</Text>
                                <Text style={[styles.cardHint, { color: theme.colors.textSecondary }]}>Tap to flip</Text>
                            </GlassView>
                        </Animated.View>

                        {/* Back Side */}
                        <Animated.View style={[
                            styles.cardFace,
                            styles.cardBack,
                            {
                                backgroundColor: theme.colors.card,
                                transform: [{ rotateY: backInterpolate }],
                                opacity: backOpacity,
                                zIndex: isFlipped ? 1 : 0,
                                borderColor: getBorderColor(currentCardIndex),
                                borderWidth: 2,
                            }
                        ]}>
                            <GlassView style={styles.glassContent} intensity={40}>
                                <Text style={[styles.cardTopic, { color: theme.colors.textSecondary }]}>{currentCard.topic}</Text>
                                <Text style={[styles.cardText, { color: theme.colors.primary }]}>{currentCard.back}</Text>
                            </GlassView>
                        </Animated.View>

                        {/* Invisible touch area for flipping */}
                        <TouchableOpacity style={StyleSheet.absoluteFill} onPress={flipCard} activeOpacity={1} />
                    </View>
                ) : (
                    <GlassView style={[styles.emptyCard, { backgroundColor: theme.colors.card }]}>
                        <Text style={{ color: theme.colors.textSecondary, textAlign: 'center' }}>
                            No flashcards yet.{'\n'}Tap the Sparkle icon to generate some!
                        </Text>
                    </GlassView>
                )}
            </View>

            <View style={styles.controls}>
                <TouchableOpacity
                    onPress={prevCard}
                    disabled={currentCardIndex === 0 || flashcards.length === 0}
                    activeOpacity={0.7}
                >
                    <GlassView
                        style={[styles.controlButton, (currentCardIndex === 0 || flashcards.length === 0) && styles.disabledButton]}
                    >
                        <ChevronLeft size={32} color={(currentCardIndex === 0 || flashcards.length === 0) ? theme.colors.textSecondary : theme.colors.primary} />
                    </GlassView>
                </TouchableOpacity>

                <Text style={[styles.counter, { color: theme.colors.textSecondary }]}>
                    {flashcards.length > 0 ? `${currentCardIndex + 1} / ${flashcards.length}` : '0 / 0'}
                </Text>

                <TouchableOpacity
                    onPress={nextCard}
                    disabled={currentCardIndex === flashcards.length - 1 || flashcards.length === 0}
                    activeOpacity={0.7}
                >
                    <GlassView
                        style={[styles.controlButton, (currentCardIndex === flashcards.length - 1 || flashcards.length === 0) && styles.disabledButton]}
                    >
                        <ChevronRight size={32} color={(currentCardIndex === flashcards.length - 1 || flashcards.length === 0) ? theme.colors.textSecondary : theme.colors.primary} />
                    </GlassView>
                </TouchableOpacity>
            </View>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 40,
    },
    headerTitle: {
        fontSize: 34,
        fontWeight: '800',
        letterSpacing: -0.5,
    },
    headerActions: {
        flexDirection: 'row',
        gap: 10,
    },
    iconButton: {
        borderRadius: 22,
        overflow: 'hidden',
    },
    glassIcon: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 40,
    },
    cardWrapper: {
        width: width - 40,
        height: 400,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyCard: {
        width: width - 40,
        height: 200,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    cardFace: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        borderRadius: 30,
        backfaceVisibility: 'hidden',
        overflow: 'hidden',
        ...Platform.select({
            web: {
                boxShadow: '0 10px 30px rgba(0,0,0,0.1)',
            },
            default: {
                elevation: 5,
            }
        }),
    },
    cardBack: {
        // No extra styles needed for backfaceVisibility hidden to work on native
    },
    glassContent: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 30,
    },
    cardTopic: {
        fontSize: 12,
        textTransform: 'uppercase',
        letterSpacing: 1,
        position: 'absolute',
        top: 30,
    },
    cardText: {
        fontSize: 28,
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: 20,
    },
    cardHint: {
        fontSize: 14,
        position: 'absolute',
        bottom: 30,
        opacity: 0.6,
    },
    controls: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 40,
        paddingHorizontal: 20,
    },
    controlButton: {
        width: 60,
        height: 60,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    disabledButton: {
        opacity: 0.5,
    },
    counter: {
        fontSize: 18,
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        width: '100%',
        maxWidth: 400,
        borderRadius: 24,
        padding: 25,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
    },
    tabRow: {
        flexDirection: 'row',
        marginBottom: 20,
        backgroundColor: 'rgba(0,0,0,0.05)',
        borderRadius: 12,
        padding: 4,
    },
    tab: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        borderRadius: 10,
        gap: 6,
    },
    tabText: {
        fontWeight: '600',
        fontSize: 14,
    },
    input: {
        height: 50,
        borderWidth: 1,
        borderRadius: 12,
        paddingHorizontal: 15,
        fontSize: 16,
        marginBottom: 20,
    },
    fileList: {
        maxHeight: 200,
        marginBottom: 20,
    },
    fileOption: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'transparent',
        marginBottom: 8,
        gap: 10,
    },
    fileOptionText: {
        fontSize: 14,
        fontWeight: '500',
    },
    generateButton: {
        flexDirection: 'row',
        height: 50,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    generateButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: '700',
    },
});

export default FlashcardsScreen;
